"""Tests for core.inventory — shared source inventory."""

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

# core/inventory/tests/test_inventory.py -> repo root
sys.path.insert(0, str(Path(__file__).parents[3]))

from core.inventory import (
    build_inventory,
    detect_language,
    compare_inventories,
    update_coverage,
    get_coverage_stats,
    format_coverage_summary,
    extract_functions,
    should_exclude,
    is_binary_file,
    is_generated_file,
    match_exclusion_reason,
    LANGUAGE_MAP,
    DEFAULT_EXCLUDES,
    GENERATED_MARKERS,
    FunctionInfo,
    PythonExtractor,
    JavaScriptExtractor,
    CExtractor,
    JavaExtractor,
    GoExtractor,
    GenericExtractor,
)


# ── Language Detection ──────────────────────────────────────────────

class TestLanguageDetection:
    def test_python(self):
        assert detect_language("foo.py") == "python"

    def test_javascript(self):
        assert detect_language("bar.js") == "javascript"
        assert detect_language("bar.jsx") == "javascript"

    def test_typescript(self):
        assert detect_language("baz.ts") == "typescript"
        assert detect_language("baz.tsx") == "typescript"

    def test_c(self):
        assert detect_language("main.c") == "c"
        assert detect_language("header.h") == "c"

    def test_cpp(self):
        assert detect_language("main.cpp") == "cpp"
        assert detect_language("main.cc") == "cpp"

    def test_java(self):
        assert detect_language("App.java") == "java"

    def test_go(self):
        assert detect_language("main.go") == "go"

    def test_rust(self):
        assert detect_language("main.rs") == "rust"

    def test_unknown(self):
        assert detect_language("readme.md") is None
        assert detect_language("data.json") is None
        assert detect_language("noext") is None

    def test_case_insensitive(self):
        assert detect_language("FOO.PY") == "python"
        assert detect_language("BAR.CPP") == "cpp"


# ── Exclusions ──────────────────────────────────────────────────────

class TestExclusions:
    def test_directory_pattern(self):
        assert should_exclude("project/tests/test_foo.py", ["tests/"]) is True
        assert should_exclude("project/src/foo.py", ["tests/"]) is False

    def test_glob_pattern(self):
        assert should_exclude("test_foo.py", ["test_*"]) is True
        assert should_exclude("foo_test.py", ["*_test.*"]) is True
        assert should_exclude("foo.py", ["test_*"]) is False

    def test_vendor_excluded(self):
        assert should_exclude("vendor/lib/foo.js", DEFAULT_EXCLUDES) is True
        assert should_exclude("node_modules/pkg/index.js", DEFAULT_EXCLUDES) is True

    def test_binary_detection(self, tmp_path):
        binary = tmp_path / "test.bin"
        binary.write_bytes(b'\x00\x01\x02\x03')
        assert is_binary_file(binary) is True

        text = tmp_path / "test.txt"
        text.write_text("hello world")
        assert is_binary_file(text) is False

    def test_generated_file_detection(self):
        assert is_generated_file("# auto-generated by protoc\ncode here") is True
        assert is_generated_file("# DO NOT EDIT\ncode here") is True
        assert is_generated_file("# my cool module\ndef foo(): pass") is False

    def test_match_exclusion_reason(self):
        excluded, reason, pattern = match_exclusion_reason(
            "project/tests/test_foo.py", ["tests/"]
        )
        assert excluded is True
        assert reason == "pattern_match"
        assert pattern == "tests/"

    def test_match_exclusion_not_excluded(self):
        excluded, reason, pattern = match_exclusion_reason(
            "src/app.py", ["tests/"]
        )
        assert excluded is False
        assert reason is None


# ── Extractors ──────────────────────────────────────────────────────

class TestPythonExtractor:
    def test_simple_function(self):
        code = "def foo(x, y):\n    return x + y\n"
        funcs = PythonExtractor().extract("test.py", code)
        assert len(funcs) == 1
        assert funcs[0].name == "foo"
        assert funcs[0].line_start == 1
        assert "def foo(x, y)" in funcs[0].signature

    def test_async_function(self):
        code = "async def fetch(url):\n    pass\n"
        funcs = PythonExtractor().extract("test.py", code)
        assert len(funcs) == 1
        assert "async" in funcs[0].signature

    def test_syntax_error_falls_back(self):
        code = "def foo(:\n    pass\ndef bar():\n    pass\n"
        funcs = PythonExtractor().extract("test.py", code)
        # Regex fallback should find bar at least
        assert any(f.name == "bar" for f in funcs)

    def test_checked_by_default_empty(self):
        code = "def foo(): pass\n"
        funcs = PythonExtractor().extract("test.py", code)
        assert funcs[0].checked_by == []


class TestJavaScriptExtractor:
    def test_function_declaration(self):
        code = "function handleRequest(req, res) {\n}\n"
        funcs = JavaScriptExtractor().extract("test.js", code)
        assert len(funcs) == 1
        assert funcs[0].name == "handleRequest"

    def test_arrow_function(self):
        code = "const handler = (req, res) => {\n}\n"
        funcs = JavaScriptExtractor().extract("test.js", code)
        assert len(funcs) == 1
        assert funcs[0].name == "handler"

    def test_skips_keywords(self):
        code = "if (x) {\n}\nfunction real() {\n}\n"
        funcs = JavaScriptExtractor().extract("test.js", code)
        assert all(f.name != "if" for f in funcs)


class TestCExtractor:
    def test_ansi_style(self):
        code = "int main(int argc, char *argv[]) {\n    return 0;\n}\n"
        funcs = CExtractor().extract("test.c", code)
        assert len(funcs) == 1
        assert funcs[0].name == "main"

    def test_split_brace(self):
        code = "int foo(int x)\n{\n    return x;\n}\n"
        funcs = CExtractor().extract("test.c", code)
        assert len(funcs) == 1
        assert funcs[0].name == "foo"

    def test_skips_keywords(self):
        code = "if (x) {\n}\nint real(void) {\n}\n"
        funcs = CExtractor().extract("test.c", code)
        assert all(f.name != "if" for f in funcs)


class TestJavaExtractor:
    def test_method(self):
        code = "public class App {\n    public void handle(Request req) {\n    }\n}\n"
        funcs = JavaExtractor().extract("App.java", code)
        assert len(funcs) == 1
        assert funcs[0].name == "handle"


class TestGoExtractor:
    def test_function(self):
        code = "func main() {\n}\n"
        funcs = GoExtractor().extract("main.go", code)
        assert len(funcs) == 1
        assert funcs[0].name == "main"

    def test_method(self):
        code = "func (s *Server) Handle(w http.ResponseWriter) {\n}\n"
        funcs = GoExtractor().extract("server.go", code)
        assert len(funcs) == 1
        assert funcs[0].name == "Handle"


class TestGenericExtractor:
    def test_generic_function(self):
        code = "def foo():\n    pass\n"
        funcs = GenericExtractor().extract("test.rb", code)
        assert len(funcs) == 1
        assert funcs[0].name == "foo"


class TestExtractFunctions:
    def test_routes_to_correct_extractor(self):
        py_code = "def foo(): pass\n"
        funcs = extract_functions("test.py", "python", py_code)
        assert len(funcs) == 1
        assert funcs[0].signature is not None  # Python extractor sets signature

    def test_unknown_language_uses_generic(self):
        code = "def foo(): pass\n"
        funcs = extract_functions("test.unknown", "ruby", code)
        assert len(funcs) == 1


# ── Build Inventory ─────────────────────────────────────────────────

class TestBuildInventory:
    def test_basic_inventory(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main():\n    pass\n")
        (src / "utils.py").write_text("def helper(x):\n    return x\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))

        assert inv["total_files"] == 2
        assert inv["total_functions"] == 2
        assert (tmp_path / "out" / "checklist.json").exists()

    def test_sha256_present(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))
        assert inv["files"][0]["sha256"]
        assert len(inv["files"][0]["sha256"]) == 64  # SHA-256 hex length

    def test_checked_by_is_list(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))
        func = inv["files"][0]["functions"][0]
        assert isinstance(func["checked_by"], list)
        assert func["checked_by"] == []

    def test_exclusion_recording(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        tests_dir = src / "tests"
        tests_dir.mkdir()
        (src / "app.py").write_text("def main(): pass\n")
        (tests_dir / "test_app.py").write_text("def test_main(): pass\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))

        assert inv["total_files"] == 1  # Only app.py
        assert len(inv["excluded_files"]) >= 1
        excluded_paths = [e["path"] for e in inv["excluded_files"]]
        assert any("test_app.py" in p for p in excluded_paths)

    def test_generated_file_excluded(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "real.py").write_text("def real(): pass\n")
        (src / "gen.py").write_text("# auto-generated by tool\ndef gen(): pass\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))

        assert inv["total_files"] == 1
        file_paths = [f["path"] for f in inv["files"]]
        assert "real.py" in file_paths
        excluded_reasons = [e["reason"] for e in inv["excluded_files"]]
        assert "generated_file" in excluded_reasons

    def test_multi_language(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")
        (src / "main.c").write_text("int main(void) {\n    return 0;\n}\n")
        (src / "app.js").write_text("function init() {\n}\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))

        languages = {f["language"] for f in inv["files"]}
        assert "python" in languages
        assert "c" in languages
        assert "javascript" in languages

    def test_nonexistent_target_raises(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            build_inventory("/nonexistent/path", str(tmp_path / "out"))


# ── Compare Inventories ─────────────────────────────────────────────

class TestCompareInventories:
    def test_identical_returns_none(self):
        inv = {"files": [{"path": "a.py", "sha256": "abc"}]}
        assert compare_inventories(inv, inv) is None

    def test_detects_added(self):
        old = {"files": [{"path": "a.py", "sha256": "abc"}]}
        new = {"files": [
            {"path": "a.py", "sha256": "abc"},
            {"path": "b.py", "sha256": "def"},
        ]}
        diff = compare_inventories(old, new)
        assert "b.py" in diff["added"]

    def test_detects_removed(self):
        old = {"files": [
            {"path": "a.py", "sha256": "abc"},
            {"path": "b.py", "sha256": "def"},
        ]}
        new = {"files": [{"path": "a.py", "sha256": "abc"}]}
        diff = compare_inventories(old, new)
        assert "b.py" in diff["removed"]

    def test_detects_modified(self):
        old = {"files": [{"path": "a.py", "sha256": "abc"}]}
        new = {"files": [{"path": "a.py", "sha256": "xyz"}]}
        diff = compare_inventories(old, new)
        assert "a.py" in diff["modified"]


# ── Cumulative Coverage ─────────────────────────────────────────────

class TestCumulativeCoverage:
    def test_carry_forward_unchanged(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        out = tmp_path / "out"

        # First run
        inv1 = build_inventory(str(src), str(out))
        # Simulate coverage
        inv1["files"][0]["functions"][0]["checked_by"] = ["validate:stage-a"]
        with open(out / "checklist.json", "w") as f:
            json.dump(inv1, f)

        # Second run (same source)
        inv2 = build_inventory(str(src), str(out))
        assert inv2["files"][0]["functions"][0]["checked_by"] == ["validate:stage-a"]

    def test_clear_modified_file(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        out = tmp_path / "out"

        # First run
        inv1 = build_inventory(str(src), str(out))
        inv1["files"][0]["functions"][0]["checked_by"] = ["validate:stage-a"]
        with open(out / "checklist.json", "w") as f:
            json.dump(inv1, f)

        # Modify source
        (src / "app.py").write_text("def main():\n    print('changed')\n")

        # Second run
        inv2 = build_inventory(str(src), str(out))
        assert inv2["files"][0]["functions"][0]["checked_by"] == []

    def test_new_file_empty_coverage(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        out = tmp_path / "out"

        # First run
        build_inventory(str(src), str(out))

        # Add new file
        (src / "new.py").write_text("def new_func(): pass\n")

        # Second run
        inv2 = build_inventory(str(src), str(out))
        new_file = next(f for f in inv2["files"] if f["path"] == "new.py")
        assert new_file["functions"][0]["checked_by"] == []


# ── Coverage Stats ──────────────────────────────────────────────────

class TestCoverageStats:
    def test_basic_stats(self):
        inv = {
            "files": [{
                "path": "app.py",
                "functions": [
                    {"name": "foo", "checked_by": ["validate:stage-a"]},
                    {"name": "bar", "checked_by": []},
                    {"name": "baz", "checked_by": ["validate:stage-a", "understand:map"]},
                ],
            }]
        }
        stats = get_coverage_stats(inv)
        assert stats["total_functions"] == 3
        assert stats["checked_functions"] == 2
        assert stats["by_source"]["validate:stage-a"] == 2
        assert stats["by_source"]["understand:map"] == 1

    def test_empty_inventory(self):
        stats = get_coverage_stats({"files": []})
        assert stats["total_functions"] == 0
        assert stats["coverage_percent"] == 0

    def test_update_coverage_appends(self):
        inv = {
            "files": [{
                "path": "app.py",
                "functions": [
                    {"name": "foo", "checked_by": []},
                ],
            }]
        }
        update_coverage(inv, [{"file": "app.py", "function": "foo"}], "validate:stage-a")
        assert "validate:stage-a" in inv["files"][0]["functions"][0]["checked_by"]

    def test_update_coverage_deduplicates(self):
        inv = {
            "files": [{
                "path": "app.py",
                "functions": [
                    {"name": "foo", "checked_by": ["validate:stage-a"]},
                ],
            }]
        }
        update_coverage(inv, [{"file": "app.py", "function": "foo"}], "validate:stage-a")
        assert inv["files"][0]["functions"][0]["checked_by"].count("validate:stage-a") == 1

    def test_format_summary(self):
        inv = {
            "total_files": 10,
            "excluded_files": [{"path": "t.py", "reason": "test"}],
            "files": [{
                "path": "app.py",
                "functions": [
                    {"name": "foo", "checked_by": ["validate:stage-a"]},
                    {"name": "bar", "checked_by": []},
                ],
            }],
        }
        summary = format_coverage_summary(inv)
        assert "10 files" in summary
        assert "1 excluded" in summary
        assert "1/2" in summary


# ── CLI Script ──────────────────────────────────────────────────────

class TestCLIScript:
    def test_build_inventory_script(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        result = subprocess.run(
            [sys.executable, "build_inventory.py", "--repo", str(src), "--out", str(tmp_path / "out")],
            capture_output=True, text=True, timeout=30,
        )
        assert result.returncode == 0
        assert "Inventory:" in result.stdout
        assert (tmp_path / "out" / "checklist.json").exists()

    def test_nonexistent_repo_fails(self, tmp_path):
        result = subprocess.run(
            [sys.executable, "build_inventory.py", "--repo", "/nonexistent", "--out", str(tmp_path)],
            capture_output=True, text=True, timeout=30,
        )
        assert result.returncode == 1
